/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import <Foundation/NSObject.h>

@class NSString, UIView, NSURL;

__attribute__((visibility("hidden")))
@interface ExtensionManager : NSObject <UIAlertViewDelegate> {
	UIView* _oldView;
	UIView* _extensionView;
//	JavaPtr<CommsManager, int> _commsManager;
	BOOL _viewTransitionSkip;
	NSString* telephoneToDialForClickToCallExtension;
	NSURL* urlToOpenInBrowser;
}
@property(retain, nonatomic) NSURL* urlToOpenInBrowser;
@property(retain, nonatomic) NSString* telephoneToDialForClickToCallExtension;
@property(readonly, assign, nonatomic) UIView* extensionView;
@property(assign, nonatomic) BOOL viewTransitionSkip;
+(id)sharedManager;
//-(id).cxx_construct;
//-(void).cxx_destruct;
-(void)didCloseExtension;
-(void)hideExtension;
-(BOOL)handleClickToOpenBrowserExtensionWithURL:(NSString*)url;
-(BOOL)handleClickToCallExtensionWithURLAsString:(id)urlasString;
-(id)parametersFromParamsAsString:(id)paramsAsString;
-(void)showTermsAndConditionsWithURL:(id)url;
-(void)showExtensionView:(id)view;
-(void)setCommsManager:(CommsManager*)manager;
-(void)dealloc;
-(id)init;
-(void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
-(void)openPhoneAppForTelephone:(id)telephone;
-(void)openSafariBrowserWithURL:(id)url;
@end

