/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import <UIKit/UIView.h>

@class UIImageView, UIImage, UITableViewCell, UIColor;

__attribute__((visibility("hidden")))
@interface MonitiseBaseTableViewCell : UIView {
	float height;
	float width;
	int myRowId;
	UIElement* myElement;
	BOOL supportRoundedCorners;
	BOOL gradient;
	UIImage* image;
	int format;
	void* parentView;
	UIColor* UIFontColor;
	BOOL selectable;
	BOOL selectChangesColor;
	float unselBGColorR;
	float unselBGColorG;
	float unselBGColorB;
	float selBGColorR;
	float selBGColorG;
	float selBGColorB;
	UIImageView* imageView;
	UITableViewCell* windowTableViewCell;
}
@property(retain, nonatomic) UITableViewCell* windowTableViewCell;
@property(retain, nonatomic) UIImageView* imageView;
@property(retain, nonatomic) UIImage* image;
@property(assign, nonatomic) BOOL supportRoundedCorners;
@property(assign, nonatomic) BOOL selectChangesColor;
@property(assign, nonatomic) BOOL selectable;
@property(assign, nonatomic) BOOL gradient;
@property(readonly, assign, nonatomic) int myRowId;
@property(assign, nonatomic) float height;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)layoutSubviews;
-(void)addToViewTable;
-(UIElement*)findParentTableElement;
-(void)setUpDisplayFromElement:(UIElement*)element BGgradient:(BOOL)ggradient;
-(void)setWidth:(float)width;
-(float)getWidth;
-(float)getHeight;
-(id)initWithFrame:(CGRect)frame;
-(void)setBackgroundColourAsTransparent;
-(void)drawRect:(CGRect)rect;
-(void)CGContextAddRoundedRect:(CGContextRef)rect rect:(CGRect)rect2 corner_radius:(int)radius;
-(void)dealloc;
@end

