/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIAlertView.h>
#import "UIAlertViewDelegate.h"
#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"


__attribute__((visibility("hidden")))
@interface MyAlertView : UIAlertView <UIAlertViewDelegate> {
	int myParagraphCount;
	UIParagraphElementRef* myParagraphElements;
	int myButtonCount;
	UIElement** myButtonElements;
}
-(void)dealloc;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)populateLabels;
@end

