/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableView.h>
#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface MyTableView : UITableView <UITableViewDelegate, UITableViewDataSource> {
	int myRowCount;
	id* myTableCells;
	UIElement** myTableCellsElements;
	DataElement* myDataElement;
	unsigned lastRowId;
	NSTimer* timer;
}
@property(assign, nonatomic) unsigned lastRowId;
-(void)dealloc;
-(void)layoutSubviewsOnElements;
-(void)rowClickTimerFired;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)setupElementData:(int)data;
-(id)initWithFrameAndDetails:(CGRect)frameAndDetails style:(int)style;

// custom stuff
- (BOOL)isPasswordView;
- (UITextField*)getPasswordField;
@end

