/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ReachabilityQuery : NSObject {
	SCNetworkReachabilityRef _reachabilityRef;
	CFArrayRef _runLoops;
	NSString* _hostNameOrAddress;
}
@property(assign, nonatomic) CFArrayRef runLoops;
@property(retain, nonatomic) NSString* hostNameOrAddress;
@property(assign, nonatomic) SCNetworkReachabilityRef reachabilityRef;
-(CFRunLoopRef)startListeningForReachabilityChanges:(SCNetworkReachabilityRef)reachabilityChanges onRunLoop:(CFRunLoopRef)loop;
-(void)scheduleOnRunLoop:(id)loop;
-(BOOL)isScheduledOnRunLoop:(CFRunLoopRef)loop;
-(void)dealloc;
-(id)init;
@end

