/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import <UIKit/UIView.h>

@class UIColor;

__attribute__((visibility("hidden")))
@interface RoundedRectView : UIView {
	UIColor* strokeColor;
	UIColor* rectColor;
	float strokeWidth;
	float cornerRadius;
}
@property(assign) float cornerRadius;
@property(assign) float strokeWidth;
@property(retain, nonatomic) UIColor* rectColor;
@property(retain, nonatomic) UIColor* strokeColor;
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(void)setOpaque:(BOOL)opaque;
-(void)setBackgroundColor:(id)color;
-(id)initWithFrame:(CGRect)frame;
-(id)initWithCoder:(id)coder;
@end

