/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import <Foundation/NSObject.h>

@class NSTimer;

__attribute__((visibility("hidden")))
@interface TimerEl : NSObject {
	NSTimer* timerTimer;
	UIElement* myElement;
	BOOL ignoreTimerResponse;
}
-(void)killTimer;
-(void)timerFired;
-(void)setUpFromElement:(UIElement*)element timoutPeriod:(int)period repeats:(BOOL)repeats;
@end

