/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import <UIKit/UINavigationBar.h>


@interface UINavigationBar (MTKitAdditions)
-(void)drawRect:(CGRect)rect;
-(void)setBackgroundImage:(id)image;
@end

