/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import "MonitiseBaseTableViewCell.h"

@class UILabel;

__attribute__((visibility("hidden")))
@interface UIParagraph : MonitiseBaseTableViewCell {
	UILabel* titleLabel;
}
@property(retain, nonatomic) UILabel* titleLabel;
-(void)layoutSubviews;
-(float)getHeight;
-(void)dealloc;
-(void)setUpDisplayFromElement:(UIElement*)element;
-(id)initWithFrame:(CGRect)frame;
@end

