/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import "MonitiseBaseTableViewCell.h"


__attribute__((visibility("hidden")))
@interface UITableCellEl : MonitiseBaseTableViewCell {
	int myRowCount;
	id* myTableCells;
	UIElement** myTableCellsElements;
}
-(void)dealloc;
-(void)layoutSubviews;
-(void)setUpDisplayFromElement:(UIElement*)element;
-(id)initWithFrame:(CGRect)frame;
@end

