/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MyView.h"
#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"

@class UIColor, UILabel, UIImageView, UIActivityIndicatorView;

__attribute__((visibility("hidden")))
@interface UIWaitScreenView : MyView {
	UIActivityIndicatorView* activityView;
	UIView* contentView;
	UILabel* waitTitle;
	UILabel* waitSubTitle;
	UIImageView* backgroundImageView;
	UIColor* textColor;
}

-(void)layoutSubviews;
-(void)setWaitScreenProperties:(id)properties subTitleText:(id)text;
-(void)stopWaitAnimation;
-(void)startWaitAnimation;
-(id)initWithTitle;
@end

