/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, MTKKeychain;

__attribute__((visibility("hidden")))
@interface MonitiseKeyChain : NSObject {
	NSString* _keyChainMigrationUID;
	MTKKeychain* _MTKKeychain;
}
+(MonitiseKeyChain*)sharedInstance;
-(id)stringForKey:(id)key;
-(BOOL)setString:(id)string forKey:(id)key;
-(BOOL)migrateFromUserDefaultsForKeys:(id)keys;
-(id)keyChainKeyFor:(id)aFor;
-(id)serviceId;
-(void)generateKeyChainMigrationUID;
-(id)generateUID;
-(void)dealloc;
-(id)init;
@end

