/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

//typedef struct _NSRange {
//	unsigned _field1;
//	unsigned _field2;
//} NSRange;

//typedef struct CGPoint {
//	float _field1;
//	float _field2;
//} CGPoint;
//
//typedef struct CGSize {
//	float _field1;
//	float _field2;
//} CGSize;
//
//typedef struct CGRect {
//	CGPoint _field1;
//	CGSize _field2;
//} CGRect;
//
typedef struct Smart Smart;

typedef struct UIElement UIElement;
//template<>
//struct JavaPtr<UIElement, int> {
//	Smart* _field1;
//	UIElement* _field2;
//};

typedef struct String String;

//template<>
//struct JavaPtr<java::lang::String, int> {
//	Smart* _field1;
//	String* _field2;
//};

struct UIElement {
	/*function-pointer*/ void** _field1;
	int _field2;
	int _field3;
	void* _field4;
	BOOL _field5;
	int _field6;
	int _field7;
	float _field8;
	int _field9;
	bool _field10;
	bool _field11;
//	bool _field12;
//	JavaPtr<UIElement, int> _field13;
//	JavaPtr<UIElement, int> _field14;
//	JavaPtr<java::lang::String, int> _field15;
//	JavaPtr<JArray<JavaPtr<UIElement, int> >, JavaPtr<UIElement, int> > _field16;
	int _field17;
	bool _field18;
	int _field19;
	int _field20;
	int _field21;
	int _field22;
	int _field23;
	int _field24;
	int _field25;
	int _field26;
	int _field27;
	int _field28;
	int _field29;
	int _field30;
	int _field31;
//	JavaPtr<java::lang::String, int> _field32;
//	JavaPtr<java::lang::String, int> _field33;
//	JavaPtr<java::lang::String, int> _field34;
//	JavaPtr<java::lang::String, int> _field35;
//	JavaPtr<java::lang::String, int> _field36;
//	JavaPtr<java::lang::String, int> _field37;
//	JavaPtr<JArray<JavaPtr<java::lang::String, int> >, JavaPtr<java::lang::String, int> > _field38;
//	JavaPtr<StyleSheetElement, int> _field39;
	bool _field40;
	int _field41;
	int _field42;
	int _field43;
	int _field44;
	int _field45;
	int _field46;
	int _field47;
	bool _field48;
	int _field49;
//	JavaPtr<java::lang::String, int> _field50;
//	JavaPtr<java::lang::String, int> _field51;
//	JavaPtr<java::lang::String, int> _field52;
//	JavaPtr<java::lang::String, int> _field53;
//	JavaPtr<java::lang::String, int> _field54;
//	JavaPtr<java::lang::String, int> _field55;
//	JavaPtr<java::lang::String, int> _field56;
//	JavaPtr<java::lang::String, int> _field57;
//	JavaPtr<java::lang::String, int> _field58;
//	JavaPtr<java::lang::String, int> _field59;
//	JavaPtr<java::lang::String, int> _field60;
//	JavaPtr<java::lang::String, int> _field61;
	int _field62;
//	JavaPtr<java::lang::String, int> _field63;
//	JavaPtr<java::lang::String, int> _field64;
	bool _field65;
	/*function-pointer*/ void** _field66;
	int _field67;
	int _field68;
	int _field69;
	int _field70;
	/*function-pointer*/ void** _field71;
	/*function-pointer*/ void** _field72;
};
//
//template<>
//struct JArray<JavaPtr<UIElement, int> >;
//
//template<>
//struct JavaPtr<JArray<JavaPtr<UIElement, int> >, JavaPtr<UIElement, int> > {
//	Smart* _field1;
//	JArray<JavaPtr<UIElement, int> >* _field2;
//};

//template<>
//struct JArray<JavaPtr<java::lang::String, int> >;
//
//template<>
//struct JavaPtr<JArray<JavaPtr<java::lang::String, int> >, JavaPtr<java::lang::String, int> > {
//	Smart* _field1;
//	JArray<JavaPtr<java::lang::String, int> >* _field2;
//};

typedef struct StyleSheetElement StyleSheetElement;
//
//template<>
//struct JavaPtr<StyleSheetElement, int> {
//	Smart* _field1;
//	StyleSheetElement* _field2;
//};

typedef struct DataElement DataElement;
//
//template<>
//struct JArray<int>;
//
//template<>
//struct JavaPtr<JArray<int>, int> {
//	Smart* _field1;
//	JArray<int>* _field2;
//};
//
typedef struct UIImageElement* UIImageElementRef;
//
//template<>
//struct JavaPtr<UIImageElement, int> {
//	Smart* _field1;
//	UIImageElementRef _field2;
//};
//
//template<>
//struct JavaPtr<DataElement, int> {
//	Smart* _field1;
//	DataElement* _field2;
//};
//
//template<>
//struct JArray<bool>;
//
//template<>
//struct JavaPtr<JArray<bool>, bool> {
//	Smart* _field1;
//	JArray<bool>* _field2;
//};

typedef struct MATMAlgorithm* MATMAlgorithmRef;
//
//template<>
//struct JavaPtr<MATMAlgorithm, int> {
//	Smart* _field1;
//	MATMAlgorithmRef _field2;
//};

typedef struct UIInputElement {
	/*function-pointer*/ void** _field1;
	int _field2;
	int _field3;
	void* _field4;
	BOOL _field5;
	int _field6;
	int _field7;
	float _field8;
	int _field9;
	bool _field10;
	bool _field11;
	bool _field12;
//	JavaPtr<UIElement, int> _field13;
//	JavaPtr<UIElement, int> _field14;
//	JavaPtr<java::lang::String, int> _field15;
//	JavaPtr<JArray<JavaPtr<UIElement, int> >, JavaPtr<UIElement, int> > _field16;
	int _field17;
	bool _field18;
	int _field19;
	int _field20;
	int _field21;
	int _field22;
	int _field23;
	int _field24;
	int _field25;
	int _field26;
	int _field27;
	int _field28;
	int _field29;
	int _field30;
	int _field31;
//	JavaPtr<java::lang::String, int> _field32;
//	JavaPtr<java::lang::String, int> _field33;
//	JavaPtr<java::lang::String, int> _field34;
//	JavaPtr<java::lang::String, int> _field35;
//	JavaPtr<java::lang::String, int> _field36;
//	JavaPtr<java::lang::String, int> _field37;
//	JavaPtr<JArray<JavaPtr<java::lang::String, int> >, JavaPtr<java::lang::String, int> > _field38;
//	JavaPtr<StyleSheetElement, int> _field39;
	bool _field40;
	int _field41;
	int _field42;
	int _field43;
	int _field44;
	int _field45;
	int _field46;
	int _field47;
	bool _field48;
	int _field49;
//	JavaPtr<java::lang::String, int> _field50;
//	JavaPtr<java::lang::String, int> _field51;
//	JavaPtr<java::lang::String, int> _field52;
//	JavaPtr<java::lang::String, int> _field53;
//	JavaPtr<java::lang::String, int> _field54;
//	JavaPtr<java::lang::String, int> _field55;
//	JavaPtr<java::lang::String, int> _field56;
//	JavaPtr<java::lang::String, int> _field57;
//	JavaPtr<java::lang::String, int> _field58;
//	JavaPtr<java::lang::String, int> _field59;
//	JavaPtr<java::lang::String, int> _field60;
//	JavaPtr<java::lang::String, int> _field61;
	int _field62;
//	JavaPtr<java::lang::String, int> _field63;
//	JavaPtr<java::lang::String, int> _field64;
	bool _field65;
//	JavaPtr<JArray<int>, int> _field66;
	int _field67;
//	JavaPtr<JArray<JavaPtr<java::lang::String, int> >, JavaPtr<java::lang::String, int> > _field68;
//	JavaPtr<UIImageElement, int> _field69;
	int _field70;
	int _field71;
	int _field72;
//	JavaPtr<DataElement, int> _field73;
	int _field74;
	int _field75;
	bool _field76;
	int _field77;
//	JavaPtr<JArray<JavaPtr<java::lang::String, int> >, JavaPtr<java::lang::String, int> > _field78;
//	JavaPtr<JArray<int>, int> _field79;
//	JavaPtr<JArray<bool>, bool> _field80;
	int _field81;
	int _field82;
//	JavaPtr<MATMAlgorithm, int> _field83;
	int _field84;
	int _field85;
	int _field86;
	int _field87;
	/*function-pointer*/ void** _field88;
	int _field89;
	int _field90;
	int _field91;
	int _field92;
	/*function-pointer*/ void** _field93;
	/*function-pointer*/ void** _field94;
} UIInputElement;

typedef struct UIParagraphElement* UIParagraphElementRef;

//typedef struct CGContext* CGContextRef;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct in_addr {
	unsigned _field1;
} in_addr;

typedef struct sockaddr_in {
	unsigned char _field1;
	unsigned char _field2;
	unsigned short _field3;
	in_addr _field4;
	BOOL _field5[8];
} sockaddr_in;

//typedef struct __CFArray* CFArrayRef;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct sqlite3 sqlite3;

typedef struct CommsManager CommsManager;
//
//template<>
//struct JavaPtr<CommsManager, int> {
//	Smart* m_Rtype;
//	CommsManager* m_RtypeTCache;
//};


