/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import "MyView.h"

@class UISelectEl, UILabel;

__attribute__((visibility("hidden")))
@interface OptionElementView : MyView {
	UILabel* titleLabel;
	UISelectEl* mySelectEl;
}
@property(retain, nonatomic) UILabel* titleLabel;
-(void)dealloc;
-(void)goBack;
-(id)initWithFrameAndDetails:(CGRect)frameAndDetails sourceElement:(id)element;
@end

