/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface PermanentCache : NSObject {
	NSString* dbPath;
	NSMutableArray* cacheItems;
	sqlite3* database;
}
@property(retain, nonatomic) NSMutableArray* cacheItems;
+(id)allocWithZone:(NSZone*)zone;
+(id)getPermanentCache;
-(void)writeCacheManagerContentsToStore;
-(void)loadStoredContentIntoCacheManager;
-(id)getDBPath;
-(void)copyDBToDeviceIfRequired;
-(id)init;
-(id)autorelease;
-(void)release;
-(unsigned)retainCount;
-(id)retain;
-(id)copyWithZone:(NSZone*)zone;
-(void)dealloc;
@end

