/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import "MonitiseBaseTableViewCell.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface UIImageEl : MonitiseBaseTableViewCell {
	UIImageView* theImageView;
	int xPosition;
}
@property(retain, nonatomic) UIImageView* theImageView;
-(void)dealloc;
-(void)setUpDisplayFromElement:(UIElement*)element;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

