/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "Monitise-iPhone-HSBC-EN-GB-Structs.h"
#import "UITextFieldDelegate.h"
#import "MonitiseBaseTableViewCell.h"

@class UITextFieldResponsive, UILabel;

__attribute__((visibility("hidden")))
@interface UIInput : MonitiseBaseTableViewCell <UITextFieldDelegate> {
	UITextFieldResponsive* textInputField;
	UILabel* titleLabel;
	UILabel* subTitleLabel;
	UILabel* textFieldCurrencyLabel;
}
@property(retain, nonatomic) UILabel* textFieldCurrencyLabel;
@property(retain, nonatomic) UILabel* subTitleLabel;
@property(retain, nonatomic) UILabel* titleLabel;
@property(retain, nonatomic) UITextFieldResponsive* textInputField;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(BOOL)textFieldShouldEndEditing:(id)textField;
-(void)setUpDisplayFromElement:(UIElement*)element;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setHint:(id)hint;
-(void)updateText;
-(id)initWithFrame:(CGRect)frame;
@end

