/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>
#import "MyTableView.h"
#import "MyView.h"
#import "UIAnchor.h"

@class UIImageView, UIImage, UIWindow;

__attribute__((visibility("hidden")))
@interface xyzApp : NSObject {
	UIImage* frameBuffer;
	UIImageView* imageView;
	UIWindow* window;
}
-(void)hideOverlayedWaitScreenInApp;
-(void)showOverlayedWaitScreenInApp;
-(void)displayFullScreenWaitScreen;
-(void)createFullScreenWaitScreen;
-(void)pseudoResponseReceived_B_Hook;
-(void)pseudoResponseReceived_I_S_Hook;
-(void)pseudoResponseReceived_AB_I_Hook;
-(void)setFirstViewHook;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)animationDidStopFlip:(id)animation;
-(void)removeKeyboard:(id)keyboard;
-(void)viewTransitionHook;
-(void)dealloc;
-(void)applicationWillEnterForeground:(id)application;
-(void)applicationDidEnterBackground:(id)application;
-(void)applicationWillResignActive:(id)application;
-(void)applicationDidBecomeActive:(id)application;
-(void)applicationWillTerminate:(id)application;
-(void)applicationDidFinishLaunching:(id)application;


// custom stuff
-(UIButton*)getNotNowButton;
-(UIApplication*)getCurrentApp;
-(UIWindow*)getCurrentWindow;
-(UIButton*)getContinueButton;
-(UIAnchor*)getContinueAnchor;
-(MyTableView*)getCurrentTableView;
-(MyView*)getCurrentMyView;
-(void)pressContinueAnchor:(NSTimer *)timer;
-(void)hideWaitscreen:(NSNotification*)notification;
@end

